import {plans,billingStatus} from '../public/plans.js';
const enc=new TextEncoder();const hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const sha=async s=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
async function hashPassword(password,salt){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:100000,hash:'SHA-256'},key,256));}
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
function same(a,b){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
export async function sessionUser(request,db){const raw=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('bloom_session='))?.slice(14);if(!raw||!/^[a-f0-9]{64}$/.test(raw))return null;return await db.prepare('SELECT users.id, users.email, users.name, users.selected_plan AS selectedPlan FROM sessions JOIN users ON sessions.user_id = users.id WHERE sessions.token_hash = ? AND sessions.expires_at > ?').bind(await sha(raw),Date.now()).first();}
function cookie(request,token,maxAge=604800){return `bloom_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${new URL(request.url).protocol==='https:'?'; Secure':''}`;}
export async function accountAPI(request,db){if(!db)return json({error:'Accounts are temporarily unavailable. Please try again later.'},503);const url=new URL(request.url),route=url.pathname;
if(route==='/api/plans'&&request.method==='GET')return json({plans,billingStatus});
if(route==='/api/account'&&request.method==='GET')return json({user:await sessionUser(request,db)});
if(request.method!=='POST')return json({error:'Method not allowed'},405);
if(request.headers.get('Origin')!==url.origin||!request.headers.get('Content-Type')?.startsWith('application/json'))return json({error:'Request not allowed'},403);
if(route==='/api/logout'){const token=(request.headers.get('Cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('bloom_session='))?.slice(14);if(token)await db.prepare('DELETE FROM sessions WHERE token_hash = ?').bind(await sha(token)).run();return json({ok:true},200,{'Set-Cookie':cookie(request,'',0)});}
if(route==='/api/plan-selection'){const user=await sessionUser(request,db);if(!user)return json({error:'Please sign in first.'},401);let input;try{input=await request.json();}catch{return json({error:'Invalid request'},400);}if(!plans.some(p=>p.id===input.planId))return json({error:'Choose a valid plan.'},400);await db.prepare('UPDATE users SET selected_plan = ? WHERE id = ?').bind(input.planId,user.id).run();return json({selectedPlan:input.planId,status:'coming_soon',active:false});}
if(!['/api/signup','/api/login'].includes(route))return json({error:'Not found'},404);
const ip=request.headers.get('CF-Connecting-IP')||request.headers.get('x-local-client-ip')||'unknown';const bucket=Math.floor(Date.now()/900000),limitKey=await sha(ip+':'+bucket);const limit=await db.prepare('INSERT INTO auth_limits (key, count, expires_at) VALUES (?, 1, ?) ON CONFLICT(key) DO UPDATE SET count = count + 1 RETURNING count').bind(limitKey,(bucket+1)*900000).first();if(limit.count>20)return json({error:'Too many attempts. Please try again in 15 minutes.'},429);
const raw=await request.text();if(raw.length>8192)return json({error:'Request too large'},413);let input;try{input=JSON.parse(raw);}catch{return json({error:'Invalid request'},400);}
const email=typeof input.email==='string'?input.email.trim().toLowerCase():'';const password=typeof input.password==='string'?input.password:'';
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>254||password.length<10||password.length>128)return json({error:'Enter a valid email and a password of 10–128 characters.'},400);
let user;
if(route==='/api/signup'){const name=typeof input.name==='string'?input.name.trim():'';if(name.length<2||name.length>80||input.adult!==true)return json({error:'Enter your name and confirm that you are a parent, guardian or teacher aged 18 or above.'},400);if(await db.prepare('SELECT id FROM users WHERE email = ?').bind(email).first())return json({error:'Unable to create this account. If you already registered, please sign in.'},409);const salt=random();user={id:crypto.randomUUID(),name,email};await db.prepare('INSERT INTO users (id, email, name, password_hash, salt, created_at) VALUES (?, ?, ?, ?, ?, ?)').bind(user.id,email,name,await hashPassword(password,salt),salt,Date.now()).run();}
else{const existing=await db.prepare('SELECT id,email,name,password_hash,salt FROM users WHERE email = ?').bind(email).first();const check=await hashPassword(password,existing?.salt||'unavailable-account-salt');if(!existing||!same(check,existing.password_hash))return json({error:'Email or password is incorrect.'},401);user={id:existing.id,email:existing.email,name:existing.name};}
const token=random();await db.prepare('INSERT INTO sessions (token_hash,user_id,expires_at) VALUES (?,?,?)').bind(await sha(token),user.id,Date.now()+604800000).run();await db.prepare('DELETE FROM auth_limits WHERE expires_at < ?').bind(Date.now()).run();await db.prepare('DELETE FROM sessions WHERE expires_at < ?').bind(Date.now()).run();return json({user},200,{'Set-Cookie':cookie(request,token)});}
